# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=7, null=True)),
                ('user_name', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('b_state', models.BooleanField()),
                ('l_state', models.BooleanField()),
                ('d_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('b_state', models.BooleanField()),
                ('l_state', models.BooleanField()),
                ('d_state', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_default_order_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_state', models.BooleanField()),
                ('l_state', models.BooleanField()),
                ('d_state', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
