# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0002_auto_20161224_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='v_state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_order',
            name='v_state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_default_order_state',
            name='v_state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
