# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0005_temp_order_make_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
