# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0006_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.CharField(default='工管組', max_length=20),
            preserve_default=False,
        ),
    ]
