# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0007_order_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
