# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0009_temporary_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temporary_order',
            new_name='None_staff_order',
        ),
    ]
