# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0011_auto_20170119_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_by_manager',
            field=models.NullBooleanField(),
        ),
    ]
